---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp economic efficiency requirements, economic efficiency prerequisites 
summary: Comece a usar a eficiência econômica do BlueXP  verificando o suporte para seu ambiente, acesso à rede, login e navegador da Web. 
---
= Pré-requisitos de eficiência econômica da BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Comece verificando a prontidão do seu ambiente operacional, login e acesso à rede.

Para usar a eficiência econômica do BlueXP , você deve garantir que seu ambiente atenda a todos os requisitos.

* Seu ambiente deve atender a todos os requisitos do BlueXP , incluindo um login e acesso à rede a partir de um navegador da Web.
+
Consulte a https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Início rápido do BlueXP"^] e https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["Informações de rede do BlueXP"^]a .

* Você precisa ter credenciais de acesso aos clusters.
* Embora não seja um requisito, é útil se o conetor BlueXP  estiver no lugar e ativado e o sistema ONTAP for descoberto. Se não, o serviço orienta você por esses processos.
* Se você planeja separar dados inativos no storage de nuvem, certifique-se de que o cluster esteja qualificado de acordo com a licença.

