---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions 
summary: 'O serviço de eficiência econômica do BlueXP  identifica clusters com baixa capacidade atual ou prevista, e fornece recomendações sobre disposição de dados em categorias ou capacidade adicional (para sistemas AFF). O serviço também fornece recomendações de atualização de tecnologia em sistemas que estão chegando ao fim da vida útil.' 
---
= O que há de novo
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba o que há de novo na eficiência econômica da BlueXP .



== 15 de maio de 2024

Alguns recursos de eficiência econômica do BlueXP  foram temporariamente desativados:

* Atualização de tecnologia
* Adicionar capacidade




== 14 de março de 2024

Se você tiver ativos existentes e quiser determinar se uma tecnologia precisa ser atualizada, use as opções de atualização da tecnologia de eficiência econômica da BlueXP . Você pode analisar uma breve avaliação de suas cargas de trabalho atuais e obter recomendações ou, se você enviou logs do AutoSupport para o NetApp nos últimos 90 dias, o serviço agora pode fornecer uma simulação de workload para ver como suas cargas de trabalho funcionam no novo hardware.

Você também pode adicionar um workload e excluir cargas de trabalho existentes da simulação.

Anteriormente, você só poderia fazer uma avaliação de seus ativos e identificar se uma atualização de tecnologia é recomendada.

O recurso agora faz parte da opção de atualização técnica na navegação à esquerda.

Saiba mais sobre o link:../use/tech-refresh.html["Avalie uma atualização de tecnologia"].



== 08 de novembro de 2023

Esta versão da eficiência econômica do BlueXP  inclui uma nova opção para fazer uma avaliação de seus ativos e identificar se uma atualização de tecnologia é recomendada. O serviço inclui uma nova opção de atualização técnica na navegação à esquerda, novas páginas onde você pode fazer uma avaliação de suas cargas de trabalho e ativos atuais e um relatório que fornece recomendações para você.



== 02 de abril de 2023

O novo serviço de eficiência econômica da BlueXP  identifica ativos de storage com baixa capacidade atual ou prevista, e fornece recomendações sobre disposição de dados em camadas ou capacidade adicional para sistemas AFF no local.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["Saiba mais sobre a eficiência econômica da BlueXP"].
